apiVersion: v1
kind: Pod
metadata:
  name: sonic-pod
  labels:
    app: sonic
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo Preparing configuration; sleep 10; echo Configuration done']
  containers:
  - name: sonic-container
    image: dazdaz/sonic
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "256Mi"
        cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: sonic-service
spec:
  type: NodePort
  selector:
    app: sonic
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30862
